-- colors
COLORS = {}

COLORS.blackColor = Color(10, 10, 10, 255)
COLORS.pureWhiteColor = Color(255, 255, 255, 255)
COLORS.whiteColor = Color(250, 250, 250, 255)
COLORS.offWhiteColor = Color(200, 200, 200, 255)
COLORS.transparent = Color(0, 0, 0, 0)

COLORS.primaryColor = Color(30, 30, 30, 255)
COLORS.secondaryColor = Color(100, 100, 100, 255)

COLORS.inRaidColor = Color(50, 255, 50, 255)
COLORS.outRaidColor = Color(255, 255, 255, 255)
COLORS.deadColor = Color(255, 50, 50, 255)
COLORS.neutralColor = Color(255, 255, 50, 255)

COLORS.statusPending = Color(0, 75, 0, 128)
COLORS.statusActive = Color(0, 0, 0, 128)
COLORS.statusEnded = Color(75, 0, 0, 128)

COLORS.menuStatusPending = Color(0, 255, 0, 255)
COLORS.menuStatusEnded = Color(255, 0, 0, 255)

COLORS.hudBackground = Color(0, 0, 0, 128)

COLORS.transparentWhiteColor = Color(255, 255, 255, 155)
COLORS.transparentBlackColor = Color(0, 0, 0, 100)
COLORS.whiteBorderColor = Color(255, 255, 255, 25)
COLORS.frameColor = Color(0, 0, 0, 240)
COLORS.scrollerColor = Color(0, 0, 0, 50)
COLORS.itemColor = Color(5, 5, 5, 20)
COLORS.itemBackgroundColor = Color(255, 255, 255, 2)
COLORS.itemBackgroundColorHovered = Color(255, 255, 255, 30)
COLORS.containerBackgroundColor = Color(80, 80, 80, 10)
COLORS.containerHeaderColor = Color(155, 155, 155, 10)
COLORS.contextBackgroundColor = Color(5, 5, 5, 50)
COLORS.contextBorder = Color(255, 255, 255, 30)
COLORS.weaponSilhouetteColor = Color(200, 200, 200, 10)
COLORS.marketItemValueColor = Color(80, 80, 80, 50)
COLORS.marketItemOutOfStockColor = Color(255, 0, 0, 15)
COLORS.tooltipBackgroundColor = Color(0, 0, 0, 205)
COLORS.tooltipBackgroundColorTransparent = Color(55, 55, 55, 45)
COLORS.tooltipHeaderColor = Color(55, 55, 55, 255)

COLORS.modelLeftColor = Color(255, 160, 80, 255)
COLORS.modelRightColor = Color(80, 160, 255, 255)

COLORS.healthGreenColor = Color(25, 255, 25, 255)

COLORS.weightUnderColor = Color(255, 255, 255, 225)
COLORS.weightWarningColor = Color(255, 255, 0, 225)
COLORS.weightMaxColor = Color(255, 0, 0, 225)

COLORS.mapWhite = Color(255, 255, 255, 240)
COLORS.mapSpawn = Color(52, 124, 218, 240)
COLORS.mapExtract = Color(19, 196, 34, 240)
COLORS.mapLocation = Color(202, 20, 20, 240)
COLORS.mapKey = Color(252, 152, 2, 240)
COLORS.mapOverviewLine = Color(202, 20, 20, 255)
COLORS.mapOverviewLoadedLine = Color(71, 5, 5, 255)
COLORS.mapOverviewUnloadedKill = Color(125, 125, 125, 240)

-- materials
MATS = {}

MATS.arrowForwardIcon = Material("icons/arrow_forward_icon.png", "smooth")
MATS.arrowBackIcon = Material("icons/arrow_back_icon.png", "smooth")
MATS.closeButtonIcon = Material("icons/close_icon.png", "smooth")
MATS.roubleIcon = Material("icons/rouble_icon.png", "smooth")
MATS.levelIcon = Material("icons/level_icon.png", "smooth")
MATS.timeIcon = Material("icons/time_icon.png", "smooth")
MATS.sellIcon = Material("icons/sell_icon.png", "smooth")
MATS.noStockIcon = Material("icons/stock_out_icon.png", "smooth")
MATS.restartIcon = Material("icons/restart_icon.png", "smooth")
MATS.favoriteIcon = Material("icons/favorite_icon.png", "smooth")
MATS.lockIcon = Material("icons/lock_icon.png", "smooth")
MATS.unlockIcon = Material("icons/unlock_icon.png", "smooth")
MATS.pinIcon = Material("icons/pin_icon.png", "smooth")
MATS.voipIcon = Material("icons/voip_icon.png", "smooth")
MATS.groupIcon = Material("icons/group_icon.png", "smooth")
MATS.sendIcon = Material("icons/send_icon.png", "smooth")
MATS.inviteSentIcon = Material("icons/invite_sent_icon.png", "smooth")
MATS.inviteErrorIcon = Material("icons/invite_error_icon.png", "smooth")
MATS.noKeyIcon = Material("icons/nokey_icon.png", "smooth")
MATS.bulletsIcon = Material("icons/bullets_icon.png", "smooth")
MATS.switchIcon = Material("icons/switch_icon.png", "smooth")
MATS.blockedIcon = Material("icons/blocked_icon.png", "smooth")
MATS.populationIcon = Material("icons/population_icon.png", "smooth")
MATS.dontEvenAsk = Material("icons/steamhappy_icon.png", "smooth")
MATS.curMapOverhad = Material("maps/" .. game.GetMap() .. ".png", "smooth")
MATS.mapSpawn = Material("icons/map/pmc_spawn_alt.png", "smooth")
MATS.mapExtract = Material("icons/map/extract_full.png", "smooth")
MATS.mapLocation = Material("icons/map/location_alt.png", "smooth")
MATS.mapKey = Material("icons/map/key.png", "smooth")
MATS.mapOverviewDeath = Material("icons/map/overview/death.png", "smooth")
MATS.mapOverviewExtract = Material("icons/map/overview/extract.png", "smooth")
MATS.mapOverviewKill = Material("icons/map/overview/kill.png", "smooth")
MATS.mapOverviewSpawn = Material("icons/map/overview/spawn.png", "smooth")
MATS.profileIcon = Material("icons/profile_icon.png", "smooth")
MATS.matchIcon = Material("icons/match_icon.png", "smooth")
MATS.inventoryIcon = Material("icons/inventory_icon.png", "smooth")
MATS.marketIcon = Material("icons/market_icon.png", "smooth")
MATS.tasksIcon = Material("icons/tasks_icon.png", "smooth")
MATS.skillsIcon = Material("icons/skills_icon.png", "smooth")
MATS.codexIcon = Material("icons/codex_icon.png", "smooth")
MATS.lockerIcon = Material("icons/locker_icon.png", "smooth")
MATS.settingsIcon = Material("icons/settings_icon.png", "smooth")
MATS.invPrimaryIcon = Material("icons/inventory_primary_icon.png", "smooth")
MATS.invHolsterIcon = Material("icons/inventory_holster_icon.png", "smooth")
MATS.invMeleeIcon = Material("icons/inventory_melee_icon.png", "smooth")
MATS.invNadeIcon = Material("icons/inventory_nade_icon.png", "smooth")
MATS.invMedicalIcon = Material("icons/inventory_medical_icon.png", "smooth")
MATS.filterAllIcon = Material("icons/sort_default_icon.png", "smooth")
MATS.filterWeaponsIcon = Material("icons/filter_weapon_icon.png", "smooth")
MATS.filterAmmunitionIcon = Material("icons/filter_ammunition_icon.png", "smooth")
MATS.filterConsumablesIcon = Material("icons/filter_medical_icon.png", "smooth")
MATS.filterAttachmentsIcon = Material("icons/sort_attach_icon.png", "smooth")
MATS.filterKeysIcon = Material("icons/filter_keys_icon.png", "smooth")
MATS.filterBarterIcon = Material("icons/filter_barter_icon.png", "smooth")
MATS.sortDefaultIcon = Material("icons/sort_default_icon.png", "smooth")
MATS.sortAlphaIcon = Material("icons/sort_alpha_icon.png", "smooth")
MATS.sortValueIcon = Material("icons/sort_value_icon.png", "smooth")
MATS.sortLevelIcon = Material("icons/sort_level_icon.png", "smooth")
MATS.sortTimeIcon = Material("icons/sort_time_icon.png", "smooth")
MATS.sortAttachIcon = Material("icons/sort_attach_icon.png", "smooth")
MATS.sortTagIcon = Material("icons/sort_tag_icon.png", "smooth")
MATS.healthIcon = Material("icons/health_icon.png", "smooth")
MATS.weightIcon = Material("icons/weight_icon.png", "smooth")
MATS.factionUSECIcon = Material("icons/usec_icon.png", "smooth")
MATS.factionBEARIcon = Material("icons/bear_icon.png", "smooth")
MATS.factionScavIcon = Material("icons/scav_icon.png", "smooth")
MATS.squadTransferIcon = Material("icons/squad_transfer_icon.png", "smooth")
MATS.squadKickIcon = Material("icons/squad_kick_icon.png", "smooth")
